-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gqllib.Object exposing (InventoryItem(..), Item(..), ItemClass(..), ItemSupply(..), Price(..), Receipt(..), SellOrder(..), SellOrderAlert(..), SubClass(..), User(..))


type InventoryItem
    = InventoryItem


type Item
    = Item


type ItemClass
    = ItemClass


type ItemSupply
    = ItemSupply


type Price
    = Price


type Receipt
    = Receipt


type SellOrder
    = SellOrder


type SellOrderAlert
    = SellOrderAlert


type SubClass
    = SubClass


type User
    = User
