-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gqllib.Subscription exposing (ReceiptRequiredArguments, SellOrderAlertRequiredArguments, price, receipt, sellOrderAlert)

import Gqllib.InputObject
import Gqllib.Interface
import Gqllib.Object
import Gqllib.Scalar
import Gqllib.ScalarCodecs
import Gqllib.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| -}
price : SelectionSet decodesTo Gqllib.Object.Price -> SelectionSet (Maybe decodesTo) RootSubscription
price object_ =
    Object.selectionForCompositeField "price" [] object_ (identity >> Decode.nullable)


type alias ReceiptRequiredArguments =
    { itemId : Int }


{-|

  - itemId -

-}
receipt : ReceiptRequiredArguments -> SelectionSet decodesTo Gqllib.Object.Receipt -> SelectionSet (Maybe decodesTo) RootSubscription
receipt requiredArgs object_ =
    Object.selectionForCompositeField "receipt" [ Argument.required "itemId" requiredArgs.itemId Encode.int ] object_ (identity >> Decode.nullable)


type alias SellOrderAlertRequiredArguments =
    { sellerName : String }


{-|

  - sellerName -

-}
sellOrderAlert : SellOrderAlertRequiredArguments -> SelectionSet decodesTo Gqllib.Object.SellOrderAlert -> SelectionSet (Maybe (List (Maybe decodesTo))) RootSubscription
sellOrderAlert requiredArgs object_ =
    Object.selectionForCompositeField "sellOrderAlert" [ Argument.required "sellerName" requiredArgs.sellerName Encode.string ] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
