-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Gqllib.Object.ItemSupply exposing (id, item, min_price, quantity)

import Gqllib.InputObject
import Gqllib.Interface
import Gqllib.Object
import Gqllib.Scalar
import Gqllib.ScalarCodecs
import Gqllib.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Float Gqllib.Object.ItemSupply
id =
    Object.selectionForField "Float" "id" [] Decode.float


{-| -}
item : SelectionSet decodesTo Gqllib.Object.Item -> SelectionSet decodesTo Gqllib.Object.ItemSupply
item object_ =
    Object.selectionForCompositeField "item" [] object_ identity


{-| -}
quantity : SelectionSet Float Gqllib.Object.ItemSupply
quantity =
    Object.selectionForField "Float" "quantity" [] Decode.float


{-| -}
min_price : SelectionSet Float Gqllib.Object.ItemSupply
min_price =
    Object.selectionForField "Float" "min_price" [] Decode.float
